### ISSUE TITLE
Issue with python setup.py build

### ISSUE THREAD

**Issue by zackvega1** [JinnnK/BNBRLplus#1]
python setup.py build
running build
running build_ext
Error: could not load cache
Traceback (most recent call last):
  File "/home/chance/BNBRLplus/BNBRLplus/Python-RVO2/setup.py", line 33, in <module>
    setup(
  File "/home/chance/anaconda3/envs/BNBRLplusConda/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/home/chance/anaconda3/envs/BNBRLplusConda/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/chance/anaconda3/envs/BNBRLplusConda/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/chance/anaconda3/envs/BNBRLplusConda/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/chance/anaconda3/envs/BNBRLplusConda/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/chance/anaconda3/envs/BNBRLplusConda/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/chance/anaconda3/envs/BNBRLplusConda/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/home/chance/anaconda3/envs/BNBRLplusConda/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/chance/anaconda3/envs/BNBRLplusConda/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/chance/anaconda3/envs/BNBRLplusConda/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/chance/BNBRLplus/BNBRLplus/Python-RVO2/setup.py", line 20, in run
    subprocess.check_call(['cmake', '--build', '.'], cwd=build_dir)
  File "/home/chance/anaconda3/envs/BNBRLplusConda/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 1.

**Comment by JinnnK** [comment]
Hello,
I apologize for the delayed response.

It seems that the issue occurred while installing RVO2.
As this package is not part of our files, we cannot provide a detailed solution. However, based on my experience, it is likely due to not meeting the prerequisites of RVO2.
Therefore, I recommend checking if the dependencies listed in the dependency file of the relevant GitHub repository have been properly installed.
